server:
  port: 8080
  mode: debug # debug, release

mysql:
  dsn: "[Your mysql dsn]"

redis:
  addr: "127.0.0.1:6379"
  password: "[Your redis password]"
  db: 0

jwt:
  secret: "[Your jwt secret]"
  expire: 72 # Token valid period 72 hours

kafka:
  addr: ["localhost:9092"] # 数组，生产环境通常是集群
  topic:
    chat: "chat_message"
    group: "group_message"
    retry: "chat_message_retry"
    dead: "chat_message_dead_letter"
  consumer_group: "chat_group"
  ack: "all" # all, 0, 1
  retry: 3