// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/oss/oss.proto

package oss

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OssService_GetUploadCredential_FullMethodName = "/oss.OssService/GetUploadCredential"
)

// OssServiceClient is the client API for OssService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 定义文件服务
type OssServiceClient interface {
	// 获取上传凭证 (对应 GetPresignedUploadUrl)
	GetUploadCredential(ctx context.Context, in *GetUploadCredentialRequest, opts ...grpc.CallOption) (*GetUploadCredentialResponse, error)
}

type ossServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOssServiceClient(cc grpc.ClientConnInterface) OssServiceClient {
	return &ossServiceClient{cc}
}

func (c *ossServiceClient) GetUploadCredential(ctx context.Context, in *GetUploadCredentialRequest, opts ...grpc.CallOption) (*GetUploadCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUploadCredentialResponse)
	err := c.cc.Invoke(ctx, OssService_GetUploadCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OssServiceServer is the server API for OssService service.
// All implementations must embed UnimplementedOssServiceServer
// for forward compatibility.
//
// 定义文件服务
type OssServiceServer interface {
	// 获取上传凭证 (对应 GetPresignedUploadUrl)
	GetUploadCredential(context.Context, *GetUploadCredentialRequest) (*GetUploadCredentialResponse, error)
	mustEmbedUnimplementedOssServiceServer()
}

// UnimplementedOssServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOssServiceServer struct{}

func (UnimplementedOssServiceServer) GetUploadCredential(context.Context, *GetUploadCredentialRequest) (*GetUploadCredentialResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUploadCredential not implemented")
}
func (UnimplementedOssServiceServer) mustEmbedUnimplementedOssServiceServer() {}
func (UnimplementedOssServiceServer) testEmbeddedByValue()                    {}

// UnsafeOssServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OssServiceServer will
// result in compilation errors.
type UnsafeOssServiceServer interface {
	mustEmbedUnimplementedOssServiceServer()
}

func RegisterOssServiceServer(s grpc.ServiceRegistrar, srv OssServiceServer) {
	// If the following call panics, it indicates UnimplementedOssServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OssService_ServiceDesc, srv)
}

func _OssService_GetUploadCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUploadCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OssServiceServer).GetUploadCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OssService_GetUploadCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OssServiceServer).GetUploadCredential(ctx, req.(*GetUploadCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OssService_ServiceDesc is the grpc.ServiceDesc for OssService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OssService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "oss.OssService",
	HandlerType: (*OssServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUploadCredential",
			Handler:    _OssService_GetUploadCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/oss/oss.proto",
}
